export default [
  "Ich muss wissen, was ich tun soll.",
  "Ich weiß nicht, was ich tun soll.",
  "Ich weiß, was für andere am besten ist.",
  "Ich weiß, was für mich am besten ist.",
  "Etwas schreckliches wird passieren.",
  "Es ist möglich, einen Fehler zu machen.",
  "Die Leute sollten nicht lügen.",
  "Die Leute sollten mich respektieren.",
  "Ich kann beeinfussen, wie andere zu mir stehen.",
  "Ich spüre deine Energie.",
  "Ich brauche mehr Geld.",
  "Das Leben ist nicht fair.",
  "Eltern sollten ihre Kinder lieben.",
  "Kinder sollten ihre Eltern lieben.",
  "Ich muss eine Entscheidung treffen.",
  "Ich kann nichts richtig machen.",
  "Ich kann Leute enttäuschen.",
  "Ich will nicht dumm aussehen.",
  "Es gibt zu viel zu tun.",
  "Es ist nicht genug Zeit.",
  "Ich weiß, was du brauchst.",
  "Ich bin wertlos.",
  "Es ist meine Aufgabe, dich glücklich zu machen.",
  "Ich brauche einen Partner um glücklich zu sein.",
  "Es ist mein Fehler.",
  "Ich sollte anders sein.",
  "Ich habe meine Chance verpasst.",
  "Ich muss im Leben vorsichtig sein.",
  "Die Leute sollten mir zuhören.",
  "Ich bin nicht gut genug.",
  "Ich bin ein Versager.",
  "_______ interessiert sich nicht für mich.",
  "Ich muss es verstehen.",
  "Ich muss es richtig machen.",
  "Ich habe es falsch gemacht.",
  "Mit mir stimmt etwas nicht.",
  "Er/Sie hat mich abgewiesen.",
  "Er/Sie vertraut mir nicht.",
  "Es sollte keinen Krieg in der Welt geben.",
  "Frauen sollten nicht so emotional sein.",
  "Leute sollten Tiere nicht benutzen (medizinische Forschung, Lebensmittel, etc.).",
  "Die Welt ist kein sicherer Ort.",
  "Die Menschen zerstören die Umwelt.",
  "Die Leute urteilen über mich.",
  "Ich weiß, was sie denken.",
  "Sie sollten mir zustimmen.",
  "Ich muss hart arbeiten.",
  "Die Menschen sollten ihre Versprechen halten.",
  "Andere können mich verletzen.",
  "Geld wird mich glücklich machen.",
  "Ich bin zu dick (dünn).",
  "Ich muss die Kontrolle haben.",
  "Mein Körper sollte gesund sein.",
  "Man kann den Leuten nicht vertrauen.",
  "_______ hat mich betrogen.",
  "Das Leben hat einen Sinn.",
  "Ich muss wissen, welchen Sinn das Leben hat.",
  "Das Leben ist schwierig.",
  "Die Menschen sollten dankbar sein.",
  "Mein Chef sollte mich anerkennen.",
  "Ich gehöre nicht dazu.",
  "Die Leute sollten nicht ärgerlich sein.",
  "_______ hat es falsch gemacht.",
  "Ich habe Recht.",
] as Array<string>;
